<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>com.io7m.sumjack</artifactId>
    <groupId>com.io7m.sumjack</groupId>
    <version>2.0.0</version>
  </parent>

  <artifactId>com.io7m.sumjack.bom</artifactId>
  <packaging>pom</packaging>

  <name>com.io7m.sumjack.bom</name>
  <description>JSON schema generator (BOM)</description>
  <url>https://www.io7m.com/software/sumjack/</url>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>com.io7m.sumjack.core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>com.io7m.sumjack.lanark</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
